- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'script-connection'
    ScriptType: 'FilePath'
    ScriptPath: 'Deploy-AzTemplate.ps1'
    ScriptArguments: '-ResourceGroupName ''demogroup'' -ResourceGroupLocation ''centralus'' -ArtifactStagingDirectory ''Templates'''
    azurePowerShellVersion: 'LatestVersion'