trigger: 
 - master

steps:
- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'script-connection'
    ScriptType: 'FilePath'
    ScriptPath: './Deploy-AzTemplate.ps1'
    ScriptArguments: -Location 'centralus' -ArtifactStagingLocation 'Templates' -ResourceGroupName 'demo'
    azurePowerShellVersion: 'LatestVersion'