- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'script-connection'
    ScriptType: 'FilePath'
    ScriptPath: 'Deploy-AzTemplate.ps1'
    ScriptArguments: 
    azurePowerShellVersion: 'LatestVersion'